###################################################################################
# MICRO SERVIÇO A — PRODUTOS (POSTGRESQL + RabbitMQ)
###################################################################################

### Health Check
GET http://localhost:8080/products/health


### Criar produto 1
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Notebook Gamer",
  "description": "RTX 4060 16GB",
  "price": 4500
}

### Criar produto 2
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Notebook Lenovo Ryzen",
  "description": "Memory 24GB",
  "price": 3800
}

### Criar produto 3
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Monitor LCD 27",
  "description": "AOC 27 Polegadas 5ms",
  "price": 989.80
}

### Criar produto 4
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Mouse Razer",
  "description": "DeathAdder Elite",
  "price": 523.06
}

### Buscar por ID
@uuid = ecf418ea-9df3-4079-98f4-276b99eafb07
GET http://localhost:8080/products/{{uuid}}

### Listar todos (PostgreSQL)
GET http://localhost:8080/products

### Deletar produto
DELETE http://localhost:8080/products/{{uuid}}

### Atualizar produto
PUT http://localhost:8080/products/{{uuid}}
Content-Type: application/json

{
  "name": "Notebook Gamer B2",
  "description": "RTX 4070 24GB",
  "price": 4950.00
}

###################################################################################
# MICRO SERVIÇO B — CATÁLOGO (Elasticsearch)
###################################################################################

### Health Check
GET http://localhost:8081/catalogo/suggest-health

###################################################################################
# BUSCA BÁSICA
###################################################################################

### Search simples
GET http://localhost:8081/catalogo/search?query=rtx

### Busca by ID
@lastId = ecf418ea-9df3-4079-98f4-276b99eafb07
GET http://localhost:8081/catalogo/products/{{lastId}}

### Busca com erro de digitação (fuzzy)
GET http://localhost:8081/catalogo/search?query=tecado

### Busca com erro (fuzzy)
GET http://localhost:8081/catalogo/search?query=notibook

### Listar tudo
GET http://localhost:8081/catalogo/search

###################################################################################
# BUSCA AVANÇADA — PAGINAÇÃO, ORDEM, CORREÇÃO (SPELLCHECK)
###################################################################################

### Busca texto
GET http://localhost:8081/catalogo/search?query=headset

### Fuzzy typing
GET http://localhost:8081/catalogo/search?query=hedsett

### Fuzzy
GET http://localhost:8081/catalogo/search?query=monitr

### Erro feio (retorna sugestões)
GET http://localhost:8081/catalogo/search?query=notbuk

### Filtro por preço
GET http://localhost:8081/catalogo/search?minPrice=3000&maxPrice=6000

### Ordenação DESC
GET http://localhost:8081/catalogo/search?sort=price&direction=desc

### Tudo junto
GET http://localhost:8081/catalogo/search?query=notebook&minPrice=3000&maxPrice=6000&page=0&size=5&sort=price&direction=asc

### Pode utilizar também o formato abaixo para ordenação
###?sort=price,asc
###?sort=price,desc
###?sort=name,asc
###?sort=name,desc

###################################################################################
# AUTOCOMPLETE
###################################################################################

### Autocomplete
GET http://localhost:8081/catalogo/suggest?prefix=no
