### parameters
### Criar produto no Microserviço A - Create product in Microservice A
POST http://localhost:8080/products
Content-Type: application/json

{
"name":"Notebook Gamer",
"description":"RTX 4060 16GB",
"price":4500
}

###
POST http://localhost:8080/products
Content-Type: application/json

{
"name":"Notebook Lenovo Ryzen",
"description":"Memory 24GB",
"price":3800
}

###
POST http://localhost:8080/products
Content-Type: application/json

{
"name":"Monitor LCD 27",
"description":"AOC 27 Polegadas 5ms",
"price":989.80
}

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "name":"Mouse Razer",
  "description":"DeathAdder Elite",
  "price":523.06
}

### Health Check Microserviço B
GET http://localhost:8081/catalogo/suggest-health

### Search Microserviço B
###
GET http://localhost:8081/search/products/rtx

###
GET http://localhost:8081/search/products/gammer

###
GET http://localhost:8081/search/products/notibook

###
GET http://localhost:8081/search/products/lcd

###
GET http://localhost:8081/search/products/minitor

### listar todos - liat all
GET http://localhost:8081/search/products/listar-todos


### Catalogo
### Busca por texto - Search by text
GET http://localhost:8081/catalogo/search?query=gamer

### Busca com erro de digitação (fuzzy) - search with error of typing
GET http://localhost:8081/catalogo/search?query=gammer

### Erro na digitação feio, não encontrado, então sugesões - bad typing, error, not found, then suggestions
GET http://localhost:8081/catalogo/search?query=notbuk

### Erro na digitação feio, não encontrado, então sugesões - bad typing, error, not found, then suggestions
GET http://localhost:8081/catalogo/search?query=minor

### Faixa de preço - Price range
GET http://localhost:8081/catalogo/search?minPrice=3000&maxPrice=6000

### Ordenação - Sorting descending
GET http://localhost:8081/catalogo/search?sort=price&direction=desc

### Buscar tudo ao mesmo tempo - Search all at the same time
GET http://localhost:8081/catalogo/search?query=noti&minPrice=3000&maxPrice=6000&page=0&size=5&sort=price,asc

### Buscar todos - List all
GET http://localhost:8081/catalogo/search

###?sort=price,asc
###?sort=price,desc
###?sort=name,asc
###?sort=name,desc


# Autocomplete
GET http://localhost:8081/catalogo/suggest?prefix=no

###